/**
 * Change-alert prototype — end-to-end.
 *
 *   TRIGGER  → detect a new model version  (poll AEC Data Model for the watched file's version)
 *   DIFF     → mp_diff_versions            (Model Properties API, SSA — no 3LO)
 *   RULES    → rules.ts                    (category/property change → discipline)
 *   ALERT    → one ACC issue per discipline (issues API; DRY-RUN by default)
 *
 * Reuses the published core SDK (`acc-forma-mcp-server/core` → ../../src/core.ts).
 *
 * Run:
 *   npx tsx prototypes/change-alert/index.mts                 # dry-run on latest two versions
 *   FORCE=1 npx tsx prototypes/change-alert/index.mts         # ignore saved state, always diff
 *   PREV=3 CUR=4 npx tsx prototypes/change-alert/index.mts    # explicit version pair
 *   CREATE_ISSUES=1 npx tsx prototypes/change-alert/index.mts # actually create the ACC issue (draft)
 */
import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { SsaAuthProvider, aecdmApi, modelPropertiesApi, issuesApi } from '../../src/core.js';
import type { DiffElement } from '../../src/apis/model-properties.js';
import { evaluateRules, groupByDiscipline, type RuleMatch } from './rules.js';

// ── Config (Ken - MCP Testing project) ─────────────────────────────────────────
const CONFIG = {
  aecdmProjectId: 'urn:adsk.workspace:prod.project:80424913-8ca5-4e39-80b0-ebf00ad69385',
  dmProjectId: '57deb033-4608-46de-ab21-fcb0404de6d3', // for MP diff + issues (no b.)
  watchModel: 'R27_Snowdon Towers Sample Architectural.rvt',
};
const __dir = dirname(fileURLToPath(import.meta.url));
const STATE_FILE = join(__dir, '.state.json');
const DRY_RUN = process.env['CREATE_ISSUES'] !== '1';

const auth = new SsaAuthProvider(['data:read', 'data:write', 'account:read']);

// ── Trigger: is there a new version of the watched model? ───────────────────────
interface WatchState { [model: string]: number }
const loadState = (): WatchState => (existsSync(STATE_FILE) ? JSON.parse(readFileSync(STATE_FILE, 'utf8')) as WatchState : {});
const saveState = (s: WatchState): void => writeFileSync(STATE_FILE, JSON.stringify(s, null, 2));
const parseVersion = (urn: string): number => Number(/version=(\d+)/.exec(urn)?.[1] ?? '0');
const lineageOf = (urn: string): string => urn.replace(/\?version=\d+$/, '');

async function detectNewVersion(): Promise<{ prevUrn: string; curUrn: string; prev: number; cur: number } | null> {
  const groups = await aecdmApi.listAecdmElementGroups(auth, CONFIG.aecdmProjectId);
  const model = groups.find((g) => g.name === CONFIG.watchModel);
  if (!model) throw new Error(`Watched model not found: ${CONFIG.watchModel}`);

  const cur = process.env['CUR'] ? Number(process.env['CUR']) : parseVersion(model.fileVersionUrn);
  const state = loadState();
  const last = process.env['PREV'] ? Number(process.env['PREV']) : (state[CONFIG.watchModel] ?? cur - 1);

  console.log(`  watched: ${CONFIG.watchModel}`);
  console.log(`  latest version: v${cur}   last processed: v${last}`);

  if (cur <= last && process.env['FORCE'] !== '1') {
    console.log('  → no new version. (set FORCE=1 to re-run, or PREV/CUR to pick a pair)');
    return null;
  }
  const lineage = lineageOf(model.fileVersionUrn);
  return { prevUrn: `${lineage}?version=${last}`, curUrn: `${lineage}?version=${cur}`, prev: last, cur };
}

// ── Alerting: turn rule matches into an ACC issue payload ───────────────────────
function renderElement(el: DiffElement): string {
  const sign = el.kind === 'ADDED' ? '+' : el.kind === 'REMOVED' ? '-' : '~';
  let line = `  ${sign} ${el.name ?? '(unnamed)'} [${el.category ?? '?'}]`;
  const fn = el.changes?.filter((c) => /Room Name|Department|Occupancy/i.test(c.field));
  if (fn && fn.length) line += '  ' + fn.map((c) => `${c.field}: ${String(c.prev)} → ${String(c.cur)}`).join(', ');
  return line;
}

function buildIssueBody(discipline: string, matches: RuleMatch[], prev: number, cur: number): { title: string; description: string } {
  const title = `[Auto] ${discipline} review — ${CONFIG.watchModel} v${prev}→v${cur}`;
  const lines: string[] = [
    `Automated change alert from the Architectural model diff (v${prev} → v${cur}).`,
    `The following changes require ${discipline} attention:`,
    '',
  ];
  for (const m of matches) {
    lines.push(`• ${m.rule.reason}  (${m.elements.length} element${m.elements.length > 1 ? 's' : ''})`);
    for (const el of m.elements.slice(0, 6)) lines.push(renderElement(el));
    if (m.elements.length > 6) lines.push(`    …and ${m.elements.length - 6} more`);
    lines.push('');
  }
  lines.push('— generated by change-alert prototype (Model Properties version diff)');
  return { title, description: lines.join('\n') };
}

async function pickIssueSubtypeId(): Promise<string | undefined> {
  const types = await issuesApi.listIssueTypes(auth, CONFIG.dmProjectId);
  for (const t of types) {
    const sub = t.subtypes?.find((s) => s.isActive !== false);
    if (sub) return sub.id;
  }
  return undefined;
}

// ── Main ───────────────────────────────────────────────────────────────────────
async function main(): Promise<void> {
  console.log('\n[1] TRIGGER — checking for a new model version…');
  const ver = await detectNewVersion();
  if (!ver) return;
  console.log(`  → NEW VERSION detected: diffing v${ver.prev} → v${ver.cur}`);

  console.log('\n[2] DIFF — Model Properties version diff (SSA)…');
  let status = await modelPropertiesApi.createVersionDiff(auth, CONFIG.dmProjectId, ver.prevUrn, ver.curUrn);
  const deadline = Date.now() + 90_000;
  while (status.state !== 'FINISHED' && status.state !== 'FAILED' && Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 4000));
    status = await modelPropertiesApi.getVersionDiff(auth, CONFIG.dmProjectId, status.diffId);
  }
  if (status.state !== 'FINISHED' || !status.fieldsUrl || !status.propertiesUrl) {
    console.log(`  diff not ready (state=${status.state}). Try again.`);
    return;
  }
  console.log(`  stats: +${status.stats?.added} added, -${status.stats?.removed} removed, ~${status.stats?.modified} modified`);

  const fields = await modelPropertiesApi.downloadDiffFields(auth, status.fieldsUrl);
  const elements = await modelPropertiesApi.downloadDiffProperties(auth, status.propertiesUrl, fields, 5000);

  console.log('\n[3] RULES — routing changes to disciplines…');
  const matches = evaluateRules(elements);
  if (matches.length === 0) {
    console.log('  no rules matched — nothing to alert.');
  } else {
    for (const m of matches) console.log(`  ✓ ${m.rule.id}: ${m.elements.length} element(s) → ${m.rule.disciplines.join(', ')}`);
  }
  const byDiscipline = groupByDiscipline(matches);

  console.log('\n[4] ALERT — ' + (DRY_RUN ? 'DRY-RUN (no issue created; set CREATE_ISSUES=1 to create)' : 'creating ACC issues (draft)') + '…');
  const subtypeId = DRY_RUN ? undefined : await pickIssueSubtypeId();

  for (const [discipline, ms] of byDiscipline) {
    const { title, description } = buildIssueBody(discipline, ms, ver.prev, ver.cur);
    console.log('\n' + '─'.repeat(70));
    console.log('TITLE:  ' + title);
    console.log(description);
    if (!DRY_RUN) {
      if (!subtypeId) { console.log('  (skip create — no active issue subtype found)'); continue; }
      const issue = await issuesApi.createIssue(auth, CONFIG.dmProjectId, {
        title, description, issueSubtypeId: subtypeId, status: 'open', published: false,
      });
      console.log(`  → created issue #${(issue as { displayId?: number }).displayId ?? '?'} (draft)`);
    }
  }

  // Persist the processed version so the next run is a no-op until a newer version appears.
  if (!DRY_RUN || process.env['SAVE_STATE'] === '1') {
    const state = loadState();
    state[CONFIG.watchModel] = ver.cur;
    saveState(state);
    console.log(`\n  state saved: ${CONFIG.watchModel} → v${ver.cur}`);
  }
}

main().catch((e) => { console.error('\nERROR:', e); process.exit(1); });
